---
title: "Live Class 1 Coding Walkthrough - BA"
author: "Matt O'Neil"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load the survey data
load('survey_data.RData')
```

Question: What is the relative level of comfort in R vs. Python?

```{r}
#take the average of R comfort
mean(r_comfort)
#take the average of python comfort
mean(py_comfort)
```
**Answer**: More students have comfort in Python than R, on average

```{r}
#comparing the median levels of comfort across the two languages
median(r_comfort)
median(py_comfort)
```
Means and Medians don't tell the whole story! We need to dig deeper
```{r}
table(r_comfort)
table(py_comfort)

table(r_comfort, py_comfort)
```

### Let's compare R and Python *individually*

```{r}
r_comfort
py_comfort
table(r_comfort <= py_comfort)
```

### Are students at least as comfortable/exposed to Python than R?
```{r}
table(r_comfort <= py_comfort)
paste0(round(mean(r_comfort <= py_comfort)*100,2),"%")
```

```{r}
mean(py_comfort[program == 'BA'])
mean(r_comfort[program=='BA'])
filter_function <- function(program_name, program_vector, comfort_vector){
  filt_vector= program_name == program_vector
  output_vector = comfort_vector[filt_vector]
  return(output_vector)
  
}

mean(filter_function('BA',program,py_comfort))
```
